### ISSUE TITLE
`strfmt("{:.0}", -0.1)` should omit negative sign

### ISSUE THREAD

**Issue by ntjess** [PgBiel/typst-oxifmt#4]
`#strfmt("{:.0}", -0.1)` displays as `-0`, where `0` would be more appropriate

**Comment by PgBiel** [comment]
This is expected behavior, as [it's how Rust does it](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=587b0afe517bd48ba8678c1cb724c33d), and this package aims to be as close as possible to Rust's `format!` function. You could use something such as

```typ
#let old-strfmt = strfmt
#let strfmt(..args) = {
  let result = old-strfmt(..args)
  if result == "-0" { "0" } else { result }
}
```

We could consider adding some sort of custom flag which just does that, but I'm not sure if it's worth it...
So I'll be closing the issue for now, but thanks for bringing this up.

**Comment by ntjess** [comment]
Thanks for the explanation, I should've checked before submitting the issue. Typst itself also formats in this way.

However, note that "-" is different from MINUS (0x2212) so you may want to change the char code such that it aligns with non-special cases:
![image](https://github.com/PgBiel/typst-oxifmt/assets/23620506/177a0735-03cd-4cf8-a3da-f79500b2278c)

**Comment by PgBiel** [comment]
Thanks @ntjess, I hadn't noticed the character was different until now! For now, I've elected a normal hyphen to be displayed in all cases instead. Perhaps we can change this in the future if needed.
